### ISSUE TITLE
Could not find artifact cz.muni.fi.mias:miasmath:jar:1.6.4-4.10.4-SNAPSHOT

### ISSUE THREAD

**Issue by sjiya** [MIR-MU/MIaS#2]
I am trying to install mias using following command 
$mvn install 
but it is giving me the following error
[ERROR] Failed to execute goal on project MIaS: Could not resolve dependencies for project cz.muni.fi.mias:MIaS:jar:1.6.4-4.10.4-SNAPSHOT: Could not find artifact cz.muni.fi.mias:miasmath:jar:1.6.4-4.10.4-SNAPSHOT

please help me.

sharraf@gmail.com

**Comment by michal-ruzicka** [comment]
Hi,

in fact you need 5 components build **in correct order**. This should work for your:

Clone and build MathML Canonicalizer

``` bash
$ git clone 'https://github.com/michal-ruzicka/MathMLCan.git'
$ cd MathMLCan/
$ git checkout master
$ mvn clean install
$ cd ..
```

Clone and build MathML Unificator

``` bash
$ git clone 'https://github.com/michal-ruzicka/MathMLUnificator.git'
$ cd MathMLUnificator/
$ git checkout master
$ mvn clean install
$ cd ..
```

Clone and build MIaS Math

``` bash
$ git clone 'https://github.com/martinliska/MIaSMath.git'
$ cd MIaSMath/
$ git checkout master
$ mvn clean install
$ cd ..
```

Clone and build MIaS

``` bash
$ git clone 'https://github.com/martinliska/MIaS.git'
$ cd MIaS/
$ git checkout master
$ mvn clean install
$ cd ..
```

Clone and build WebMIaS

``` bash
$ git clone 'https://github.com/martinliska/WebMIaS.git'
$ cd WebMIaS/
$ git checkout master
$ mvn clean install
$ cd ..
```

Now you are done with all the components ready:

``` bash
$ ls -1 */target/*-jar-with-dependencies.jar
MathMLCan/target/mathml-canonicalizer-1.3.1-jar-with-dependencies.jar
MathMLUnificator/target/mathml-unificator-1.1.0-jar-with-dependencies.jar
MIaSMath/target/miasmath-1.6.4-4.10.4-SNAPSHOT-jar-with-dependencies.jar
MIaS/target/MIaS-1.6.4-4.10.4-SNAPSHOT-jar-with-dependencies.jar
```

**Comment by sjiya** [comment]
Thanks for help. 
problem is solved.

**Comment by sjiya** [comment]
Thank you for helping me to install MIaS completely. Now I am trying to
make an index of "MREC2011.3.324" directory using following command;

java -jar MIaS-1.6.4-4.10.4-SNAPSHOT-jar-with-dependencies.jar -add
/home/sharaf/Data_MIaS/MREC2011.3.324/ /home/sharaf/Data_MIaS/index/

but it is giving me the help in output

usage: MIaS
 -add <input_path> <root_dir>            where root_dir is an absolute
                                         path to a directory in the
                                         input_path to determine the
                                         relative path that the files will
                                         be indexed with
 -conf <arg>                             Path to indexing configuration
                                         file.
 -delete <dir_or_file>                   Deletes file(s) from index.
 -deleteindex                            Deletes the index.
 -indocprocess <input_path> <root_dir>   where root_dir is an absolute
                                         path to a directory in the
                                         input_path. Processes math
                                         formulae and inserts M-terms into
                                         documents created under root_dir.
 -optimize                               Optimizes the index for maximum
                                         searching performance.
 -overwrite <input_path> <root_dir>      Overwrites existing index
 -stats                                  Prints statistics about index.

what should I do for creating index? what about _mias.to http://mias.to_
file and where should I locate it?

Regards,
Sharaf Hussain

**Comment by martinliska** [comment]
Dear Sharaf,

sorry for the troubles. The info in README.txt is a little out-of-date. Will update it right away.

You need to specify -conf option with a path to the main configuration file. mias.to is no longer used for this. The path is specified directly on the command line. So your command line should look like this
java -jar MIaS-1.6.4-4.10.4-SNAPSHOT-jar-with-dependencies.jar -conf /home/sharaf/Data_MIaS/mias.properties -add /home/sharaf/Data_MIaS/MREC2011.3.324/ /home/sharaf/Data_MIaS/index/

Thanks

Martin

**Comment by sjiya** [comment]
Dear Martin,
Thanks for the information. now the index is made but I have two questions,
1. can print the index? if yes, then how?
2. how can I run the query and search from the index? what command and
format is available?

Regards,
Sharaf Hussain

**Comment by michal-ruzicka** [comment]
>  1. can print the index? if yes, then how?

The index is the [Lucene](https://lucene.apache.org/) one. You can use any tool available for the Lucene index. To be hones, I do not have any favourite tool. How about [Luke](https://github.com/DmitryKey/luke)?

If you will find any better tool do not hesitate to post link here.

>  2. how can I run the query and search from the index? what command and format is available?

You can integrate you own tool using [MIaS search functionality](https://github.com/martinliska/MIaS/blob/master/src/main/java/cz/muni/fi/mias/search/Searching.java#L90).

However, for testing it is far more convenient to use [WebMIaS](https://github.com/martinliska/WebMIaS) – web search interface accepting mixed text and math queries (math in MathML or TeX notation). Simply [set index name and paths](https://github.com/martinliska/WebMIaS/blob/master/src/main/resources/cz/muni/fi/webmias/indexes.properties) and deploy the WebMIaS on Tomcat server.

**Comment by michal-ruzicka** [comment]
@sjiya BTW, you are just trying MIaS or you are interested in development / comparison with your own system / deployment of MIaS somewhere / ...?

**Comment by sjiya** [comment]
Dear Ruzicka,
Luke is not able to open MIaS inde., I have tried on smaller, larger and
other different size indexes on different format.
I am developing my own Mathematical Information Retrieval(MIR) system based
on tree structure, I have done few experiments and found that tree like
structure techniques index and retrieved documents more efficiently than
other indexing techniques. I am also exploring various developing
techniques for MIR, like MIaS techniques and trying to compare the results.

Regards,
Sharaf Hussain

**Comment by michal-ruzicka** [comment]
Hi,

Dne 27.7.2016 v 9:37 sjiya napsal(a):

> Dear Ruzicka,
> Luke is not able to open MIaS inde., I have tried on smaller, larger and
> other different size indexes on different format.

you have to use the right version of Luke corresponding with Lucene
version used by MIaS as index format is incompatible otherwise. This
works for me:

$ git clone 'https://github.com/DmitryKey/luke.git' luke.git
$ cd luke.git
$ git checkout luke-4.10.4
$ mvn clean install
$ java -jar target/luke-with-deps.jar

> I am developing my own Mathematical Information Retrieval(MIR) system based
> on tree structure, I have done few experiments and found that tree like
> structure techniques index and retrieved documents more efficiently than
> other indexing techniques.

Do you work on (Presentation and/or Content?) MathML XML trees?

> I am also exploring various developing
> techniques for MIR, like MIaS techniques and trying to compare the results.

Very interesting. Do you have published a paper on you technique? Our
group would be very interesting in getting more info about your method.
Do you know the NTCIR MathIR (http://ntcir-math.nii.ac.jp/)?

Thanks,
Michal

**Comment by sjiya** [comment]
On Wed, Jul 27, 2016 at 12:49 PM, Michal Růžička notifications@github.com
wrote:

> Hi,
> 
> Dne 27.7.2016 v 9:37 sjiya napsal(a):
> 
> > Dear Ruzicka,
> > Luke is not able to open MIaS inde., I have tried on smaller, larger and
> > other different size indexes on different format.
> 
> you have to use the right version of Luke corresponding with Lucene
> version used by MIaS as index format is incompatible otherwise. This
> works for me:
> 
> $ git clone 'https://github.com/DmitryKey/luke.git' luke.git
> $ cd luke.git
> $ git checkout luke-4.10.4
> $ mvn clean install
> $ java -jar target/luke-with-deps.jar

Thanks, now luke is working fine.

> > I am developing my own Mathematical Information Retrieval(MIR) system
> > based
> > on tree structure, I have done few experiments and found that tree like
> > structure techniques index and retrieved documents more efficiently than
> > other indexing techniques.
> 
> Do you work on (Presentation and/or Content?) MathML XML trees?

I am working on CMML and using context trees (
http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.12.9907 ) for
indexing.

> > I am also exploring various developing
> > techniques for MIR, like MIaS techniques and trying to compare the
> > results.
> 
> Very interesting. Do you have published a paper on you technique? Our
> group would be very interesting in getting more info about your method.

I am just finalizing the paper related related to my technique.

Do you know the NTCIR MathIR (http://ntcir-math.nii.ac.jp/)?


Yes, I know about NTCIR MathIR and will must target when my system is
ready.

**Comment by michal-ruzicka** [comment]
OK, thanks. --mr

Dne 27.7.2016 v 12:58 sjiya napsal(a):

**Comment by pathakamarnath** [comment]
Hello Sir,

I am able to build only MathMLCan and MathML Unifactor. When I am trying to build MIaS Math and others then it shows following error:  

Could not resolve dependencies for project cz.muni.fi.mias:miasmath:jar:1.6.6-4.10.4-SNAPSHOT: Could not find artifact cz.muni.fi.mir:mathml-canonicalizer:jar:1.4.0-SNAPSHOT.

Please help me out.

Thanks!

Amarnath Pathak

**Comment by michal-ruzicka** [comment]
Hi, @pathakamarnath, you have to build all the tool the right order. See the [second comment](https://github.com/martinliska/MIaS/issues/2#issuecomment-230146754).

**Comment by pathakamarnath** [comment]
Sir I am building them in correct order as given in second comment but when I am trying to clone and build the third one i.e. MIaS Math then it starts showing the error: 
Could not resolve dependencies for project cz.muni.fi.mias:miasmath:jar:1.6.6-4.10.4-SNAPSHOT: Could not find artifact cz.muni.fi.mir:mathml-canonicalizer:jar:1.4.0-SNAPSHOT.

Please help me out.

Thanks!


Amarnath Pathak

**Comment by michal-ruzicka** [comment]
@pathakamarnath Sorry, I see the problem now. The MIaS Math version you are using references a development snapshot of the MathML Canonicalizer. You have to switch to the [develop](https://github.com/michal-ruzicka/MathMLCan/tree/develop) branch of MathML Canonicalizer when building it. It will produce the 1.4.0-SNAPSHOT version the MIaS Math needs.

**Comment by sjiya** [comment]
I am running it on Ubuntu and it is working fine. Which os are you using?

**Comment by pathakamarnath** [comment]
Sir could you please elaborate. As instructed by you I just tried 
git clone 'https://github.com/michal-ruzicka/MathMLCan/tree/develop'
but even this doesn't work.

And thank you so much Sir for your valuable comment.

**Comment by michal-ruzicka** [comment]
@pathakamarnath The URL is not for cloning. You have to learn to use Git: https://git-scm.com/doc

**Comment by pathakamarnath** [comment]
@sjiya Sir even I am also running it on Ubuntu.

**Comment by sjiya** [comment]
Dear Martin Liska,
I have made an index by using your MIaS indexing application and I observed
that it is making pmml index(pmath). can we make an index of cmml structure
by using your code OR what changes I need to make in your code for making
cmml index.

Regards,
Sharaf Hussain

**Comment by michal-ruzicka** [comment]
@sjiya Dear Sharaf Hussain, cmml should be part of the indexed data as long as they are part of the MathML tree of the input formulae. No special action is required. You can inspect contents of the Lucene index using [Luke](http://www.getopt.org/luke/), for example.

![cmml-in-lucene-index](https://cloud.githubusercontent.com/assets/5677221/23309220/1b41a3f0-faae-11e6-9dfd-1b0fc1797f1f.png)

**Comment by sjiya** [comment]
Dear Ruzicka,
I am sending you the file that I am using for making an index. it contains
PMML and CMML code, but in index output, it is only giving "pmath" tags.
would you please tell me the problem. I would appreciate you if you can
make an index of attached file at your end and tell me the result?

Regards,
Sharaf Hussain

**Comment by michal-ruzicka** [comment]
@sjiya I am afraid the attachment was not delivered when send to when sent to the GitHub system.

**Comment by sjiya** [comment]
please provide me your other email address where I can send you the
attachment.

Regards,
Sharaf Hussain

**Comment by michal-ruzicka** [comment]
@sjiya Ok, let's keep our discussion documented on GitHub:

I have received your e-mail with sample file [exp2cmml.zip](https://github.com/martinliska/MIaS/files/810190/exp2cmml.zip) asking for help with CMML indexing.

Before I managed to look at it (very sorry, I am working on another short term project with high priority now) you sent me another message:

> Dear Ruzicka,
> CMML indexing is running. Can you provide me the executable file for searching results from
> index? because executable searching java file is not available in the code.
> 
> Regards,
> Sharaf Hussain

So CMML indexing is finally running on your site (what was the problem, by the way? it should be working out-of-the-box).

Searching: For search you can use separate Java web application – [WebMIaS](https://mir.fi.muni.cz/webmias/). Is is a web interface. Just point it out to your index (in `src/main/resources/cz/muni/fi/webmias/indexes.properties`) and deploy to Apache Tomcat, for example. You can try our [on-line demo](https://mir.fi.muni.cz/webmias-demo/).

**Comment by sjiya** [comment]
Dear Ruzicka,
Thank you for a reply.
I have mad few changes in the code, which are as follows

*1. Class : CountNodesFormulaValuator. java*
*Method: value*
*commented line 33: //mmlType = MathTokenizer.MathMLType.PRESENTATION;*
*add line 34: mmlType = MathTokenizer.MathMLType.BOTH;*

*2. Class: FormulaDocument.java*
*Method: getDocument*
*commented line 74 -79 : *
*/* MathTokenizer mathTokenizer = new MathTokenizer(isr, true,
MathTokenizer.MathMLType.PRESENTATION);*
*                mathTokenizer.setFormulaPosition(i+1);*
*                doc.add(new TextField("pmath", mathTokenizer));*
*                is.reset();*
*                isr = new InputStreamReader(is, "UTF-8");*/*
Now it is indexing only CMML components only.

I have checked src/main/resources/cz/muni/fi/webmias/indexes.properties File
INDEX_NAMES=DEV (??)
PATHS=D:\\skola\\mir\\projects\\indexes\\index-test (Index directory Path)
STORAGES=d:\\skola\\mir\\NTCIR11\\ (Documents Directory Path)
MAXRESULTS=10000 (Maximum Limits of Results)

but unable to get the meaning of first option INDEX_NAMES=DEV, can you
please explain it?

Regards,
Sharaf Hussain

**Comment by michal-ruzicka** [comment]
> but unable to get the meaning of first option INDEX_NAMES=DEV, can you please explain it?

It's simply an index name shown in ‘Search in:’ index selection menu of WebMIaS. Feel free use arbitrary value describing the index for your, for example ‘my-cmml-index’.

**Comment by sjiya** [comment]
Dear Liska ,
I want to use NTCIR-12 Arixv collection of documents for performing my
research experiments. can you please provide me the link of  NTCIR-12 ARXIV
collection?

Regards,
Sharaf Hussain

**Comment by michal-ruzicka** [comment]
Dear @sjiya, the dataset is available at [NTCIR Math IR website](http://ntcir-math.nii.ac.jp/data/).

All the best
Michal

**Comment by sjiya** [comment]
Dear Ruzica,
Thank you for prompt response. Only wikipedia dataset is available at
http://ntcir-math.nii.ac.jp/data/ but Arxiv link is not there. please
provide me the link If you have the dataset.

Regards,
Sharaf Hussain

**Comment by michal-ruzicka** [comment]
@sjiya NTCIR-12 used the same dataset as NTCIR-11, i.e. the correct link for you is [http://research.nii.ac.jp/ntcir/permission/ntcir-11/perm-en-MATH.html](http://research.nii.ac.jp/ntcir/permission/ntcir-11/perm-en-MATH.html).

--mr

**Comment by sjiya** [comment]
Dear Ruzika,
I have visited the NTCIR 11 web site
http://research.nii.ac.jp/ntcir/ntcir-11/data.html#math but not found any
link for ARXIV data. If you have the correct link please provide me.

Thanks & Regards,
Sharaf Hussain

**Comment by michal-ruzicka** [comment]
@sjiya I provided you with [correct link](http://research.nii.ac.jp/ntcir/permission/ntcir-11/perm-en-MATH.html#obtain). The collection is available against NDA for research purpose only. The application can be filled in at [http://www.nii.ac.jp/dsc/idr/en/ntcir/ntcir.html](http://www.nii.ac.jp/dsc/idr/en/ntcir/ntcir.html) that is referenced from the URL I provided you.

I am afraid I am unable to help you more with the exact procedure. It is very long time we were asking for the data. I do not know the current procedure. Ask NTCIR team for help if you encounter any difficulties.
